---
title: "MÜY665-Ödev 1"
author: "Selcan İşlek"
date: "2026-03-08"
format: html
---

```{r}
# label: k-hesaplama

# echo: true

# Değişkenlerin tanımlanması

my_first <- "Selcan"
my_birth_year <- 1997

# k değerinin hesaplanması

k <- (nchar(my_first) + my_birth_year) %% 15 + 8

print(paste("Hesaplanan k degeri:", k))
```

```{r}

##| label: veri-hazirlik
##| #| message: false 
##| #| warning: false

# Gerekli paketlerin kontrolü ve yüklenmesi

if (!require("dslabs")) install.packages("dslabs")
if (!require("dplyr")) install.packages("dplyr")

library(dslabs) 
library(dplyr)

# Veriyi içe aktarma

data("polls_us_election_2016")
```

```{r}

#| label: veri-isleme 
#| # k çift ise head, tek ise tail fonksiyonu seçilir 
#| if (k %% 2 == 0) { 
#| # k çift olduğu için head kullanıyoruz 
#| secilen_veri <- head(polls_us_election_2016, k) 
#| } else { 
#| # k tek olsaydı tail kullanacaktık 
#| secilen_veri <- tail(polls_us_election_2016, k) }

# Eksik verileri (NA) temizleme

temiz_veri <- na.omit(secilen_veri)

#| label: tablo-cikti 
#| knitr::kable(temiz_veri)
```
